application: goahead
version: 0.0.0
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: css
  
- url: /font
  static_dir: font

- url: /img
  static_dir: img
  
- url: /js
  static_dir: js
  
- url: /.*
  script: _go_app
